name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.2"
        - "24.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.3
      with:
        otp-version: ${{ matrix.otp }}
    - name: XREF
      run: make xref
    - name: DEPS
      run: make test-deps
    - name: DIALYZE
      run: make dialyze
    - name: BUILD
      run: make test-build
    - name: EUNIT
      run: make eunit
    - name: COMMON TEST
      run: make ct
    - name: PROPER
      run: make proper
    - name: CAPTURE TEST LOGS ON FAILURE
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ct-logs-${{matrix.otp}}
        path: logs/*
  build-bazel:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.2"
        - "24.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.3
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        cat << EOF >> .bazelrc
          build --@rules_erlang//:erlang_version=${{ matrix.erlang_version }}
          build --@rules_erlang//:erlang_home=${ERLANG_HOME}

          build --incompatible_strict_action_env

          build --test_strategy=exclusive
        EOF
    - name: TEST
      run: |
        bazelisk test //...
    - name: RESOVLE TEST LOGS PATH
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS ON FAILURE
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: bazel-testlogs-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*